import {Queue,Worker} from "bullmq";
import path from "path";
import IORedis from "ioredis";
import dotenv from "dotenv";
import { createClient } from "@supabase/supabase-js";

import {checkYoutubeUrl} from "../services/fetchTranscript.js";
import {fetchSingleVideoTranscript, fetchPlaylistVideoIds} from "../services/fetchTranscript.js";
import { cleanTranscript,chunkText } from "../services/chunkText.js";
import { embedChunks } from "../services/embedChunks.js";
import { extractConcepts } from "../services/extractConcepts.js";
import { title } from "process";
import {Graph} from "../services/buildGraphs.js";
import { generateQuestions } from "../services/generateQuestions.js";

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const REDIS_URL = process.env.REDIS_URL || 'redis://127.0.0.1:6379';

const connection = new IORedis(REDIS_URL,{maxRetriesPerRequest: null}); // Required by BullMQ to prevent connection drops

const ingestQueue = new Queue("youtube-ingestion",{connection});    //Queue creation

const ingestWorker = new Worker("youtube-ingestion",async (job)=>{  //Worker creation
    const {url,userId} = job.data;
    console.log(`Processing job with job id ${job.id} and url ${url}`);
    try{
        await job.updateProgress(10);
        
        //if the job is of concept extraction
        if(job.name == "extract-concepts"){
            let {chunks,playlistId,videoId,videoMinutes} = job.data;
            const maxConcepts = Math.min(Math.max(4, Math.floor(4+videoMinutes/3)),20);
            const graphDataObj = await extractConcepts(chunks,maxConcepts);
            const concepts = graphDataObj.concepts;
            const prerequisites = graphDataObj.prerequisites;
            
            //Deduplicate Concepts
            const conceptNames = concepts.map(c => c.name);
            const conceptEmbeddObj = await embedChunks(conceptNames);
            const conceptEmbeddings = conceptEmbeddObj.data;

            const conceptsWithVectors = concepts.map((conceptObj, index) => {
                return {
                    id: conceptObj.id,
                    name: conceptObj.name,
                    description: conceptObj.description,
                    concept_embedding: conceptEmbeddings[index] // matched by index!
                };
            });

            const formattedStringVectors = conceptEmbeddings.map(vec => `[${vec.join(',')}]`);
            //finding matched concepts so that we can merge easily , the similar concepts
            const { data: matchedDbConcepts, error } = await supabase.rpc('match_concepts_batch', {
                concept_embeddings: formattedStringVectors,
                match_threshold: 0.85 // adjustable similarity threshold
            });

            if (error) {
                console.error("RPC Error:", error.message);
                throw error;
            }

            let uniqueConcepts = [];
            const slugToPostgresIdMap = {}; //needed to map the prerequites source and target concept actual ids 
            //it is because the the id generated by LLM is slug-integer type and not a int,
            //int is assigned directly by postgres so we need that to resue in prerequisites table

            for(let c of conceptsWithVectors){
                let skipInsertion = false;
                for(let dbConcept of matchedDbConcepts){
                    let score = similarity(c.concept_embedding,dbConcept.concept_embedding);
                    if(score>=0.85){
                        slugToPostgresIdMap[c.id] = dbConcept.id;
                        skipInsertion = true;
                        break;
                    }
                }
                if(skipInsertion) continue;
                for(let concept of uniqueConcepts){
                    let score = similarity(c.concept_embedding,concept.concept_embedding);
                    if(score>0.85){
                        //both c and concept are twins and yet to be inserted 
                        slugToPostgresIdMap[c.id] = concept;  //stored direct reference bcz this data has not yet been inserted
                        skipInsertion = true;
                        break;
                    }
                }
                if(skipInsertion) continue;
                uniqueConcepts.push(c);
            }


            let insertPayloadForConcepts = uniqueConcepts.map((concept,index)=>{
                return{
                    playlist_id:playlistId,
                    video_id: videoId,
                    name:concept.name,
                    concept_embedding: concept.concept_embedding,
                    description: concept.description,
                };
            });

            if (insertPayloadForConcepts.length > 0) {
                const {data:insertedConcepts, error:conceptError} = await supabase.from('concepts').insert(insertPayloadForConcepts)
                .select("id,name");   //this tells supabase to return actual ids and name

                if(conceptError) throw conceptError;
                //finding actual ids for slug-ids
                insertedConcepts.forEach(dbConcept=>{
                    const matchingLlmConcept = concepts.find(c=>c.name === dbConcept.name);
                    if(matchingLlmConcept){
                        //lhs is a string, rhs is a number
                        slugToPostgresIdMap[matchingLlmConcept.id] = dbConcept.id;
                    }
                });

                // Resolve local batch duplicates that pointed to an object instead of an integer ID
                conceptsWithVectors.forEach(c => {
                    if(slugToPostgresIdMap[c.id] && typeof slugToPostgresIdMap[c.id] === 'object'){
                        const targetObj = slugToPostgresIdMap[c.id];
                        slugToPostgresIdMap[c.id] = slugToPostgresIdMap[targetObj.id];
                    }
                });
            }

            let insertPayloadForPrerequisites = prerequisites.map((prerequisite,index)=>{
                return{
                    playlist_id:playlistId,
                    video_id: videoId,
                    source_concept_id:slugToPostgresIdMap[prerequisite.source],
                    target_concept_id:slugToPostgresIdMap[prerequisite.target],
                };
            }).filter(edge => edge.source_concept_id !== undefined && edge.target_concept_id !== undefined);
            //this above line is a extra safety check which is added to filter out only non undefined key value pairs
            const {data:insertedPrerequisites, error:prerequisitesError} = await supabase.from('concept_edges').insert(insertPayloadForPrerequisites);
            if(prerequisitesError) throw prerequisitesError;

            console.log(`Knowledge graph synthesis finalized successfully.`);

            //Topo Sort and Cycle Resolution
            console.log("Starting Topological Sorting of concepts....");

            //only fetch concept and edges for current playlist not the previous ones
            const {data: currentConcepts} = await supabase
            .from("concepts").select("id").eq("video_id",videoId);

            const {data: currentEdges} = await supabase
            .from("concept_edges").select("source_concept_id,target_concept_id")
            .eq("video_id",videoId);

            const conceptIds = currentConcepts.map(c => c.id);
            const formattedEdges = currentEdges.map(e => ({
                source_id: e.source_concept_id,
                target_id: e.target_concept_id
            }));

            const sorter = new Graph(conceptIds, formattedEdges);     //new object of Graph class
            const sortResult = sorter.topoSort();
            const linearSequence = sortResult.sequence;

            for (let i = 0; i < linearSequence.length; i++) {
                const conceptId = linearSequence[i];
                // Save the current index 'i' as the 'sort_order' for this concept
                await supabase
                    .from('concepts')
                    .update({ sort_order: i })
                    .eq('id', conceptId);
            }

            //Removing broken edge from the database
            if(sortResult.mutated && sortResult.brokenEdges.length>0){
                console.log("Cleaning up the database for broken edges...");
                for(let i = 0; i < sortResult.brokenEdges.length; i++){
                    const edge = sortResult.brokenEdges[i];  
                    await supabase
                        .from('concept_edges')
                        .delete()
                        .eq('source_concept_id', edge.source_id)
                        .eq('target_concept_id', edge.target_id);
                    console.log(`Deleted circular edge from DB: ${edge.source_id} ➔ ${edge.target_id}`);
                }
            }
            await ingestQueue.add("generate-assessment", {
                videoId: videoId
            });

            console.log(`[QUEUE] Successfully queued Stage 4 assessment generation for video: ${videoId}`);

            return { success: true, stage: "graph-extraction" };

        }

        if(job.name == "generate-assessment"){
            const {videoId,unifiedTranscript} = job.data;
            console.log(`[ASSESSMENT WORKER] Launching single-pass batch generation for video: ${videoId}`);
            await job.updateProgress(10);

            const {data: concepts,error: fetchError} =  await supabase
            .from("concepts")
            .select("id, name, description")
            .eq("video_id",videoId)
            .order("sort_order",{ascending:true});

            if (fetchError || !concepts || concepts.length === 0) {
                console.error(`[ASSESSMENT WORKER] Aborting. Failed to retrieve active graph nodes:`, fetchError);
                throw new Error(fetchError.message || "No concepts found for assessment mapping");
            }
            await job.updateProgress(30);

            const resultObj = await generateQuestions(concepts,unifiedTranscript);

            if(!resultObj.success || !resultObj.assessments){
                throw new Error("Bulk assessment matrix extraction failed or parsed incorrectly.");
            }

            // // 2. 🧠 THE FIXED STRATEGY: Loop through concepts item-by-item
            // for (let index = 0; i < concepts.length; i++) {
            //     const singleConcept = concepts[index];
            //     console.log(`[ASSESSMENT WORKER] Processing concept (${index + 1}/${concepts.length}): ${singleConcept.name}`);

            //     // Fetch a highly restricted subset of chunks linked to this specific video
            //     // This acts as a tight sliding window to ensure your request stays around 2,000-4,000 tokens
            //     const { data: textChunks, error: chunkError } = await supabase
            //         .from("chunks")
            //         .select("content")
            //         .eq("video_id", videoId)
            //         .limit(4); // 👈 TIGHT CONSTRAINT: Safely limits token usage well below the 12k TPM threshold

            //     if (chunkError || !textChunks || textChunks.length === 0) {
            //         console.warn(`[ASSESSMENT WORKER] No chunks found for video context window, skipping concept context.`);
            //         continue;
            //     }

            //     const focusedContextText = textChunks.map(c => c.content).join("\n");

            //     try {
            //         // Send exactly ONE concept with its dedicated local text context per trip
            //         const resultObj = await generateQuestions([singleConcept], focusedContextText);
                    
            //         if (resultObj && resultObj.assessments && resultObj.assessments.length > 0) {
            //             finalAssessments.push(resultObj.assessments[0]);
            //         }

            //         // ⏱️ RATE LIMIT BREAKER: Insert a slight delay to allow the rolling TPM counter to reset
            //         await new Promise((resolve) => setTimeout(resolve, 2000));

            //     } catch (apiErr) {
            //         console.error(`[GROQ API EXCEPTION] Failed processing concept ${singleConcept.id}:`, apiErr.message);
            //         // Propagate the failure so the queue knows to try again later
            //         throw apiErr; 
            //     }
            // }

            await job.updateProgress(60);
            console.log(`[ASSESSMENT WORKER] Structurally parsed ${resultObj.assessments.length} assessment blocks. Writing records...`);

            for(const entry of resultObj.assessments){
                const targetConceptId = entry.concept_id;
                
                const questionsPayload = entry.mcqs.map(m => {
                const correctIndexPointer = m.options.findIndex(opt => opt.is_correct === true);

                const rawDiff = m.difficulty;
                let computedLevel = 1;
                if (rawDiff === 2 || String(rawDiff).toLowerCase() === 'medium') {
                    computedLevel = 2;
                } else if (rawDiff === 3 || String(rawDiff).toLowerCase() === 'hard') {
                    computedLevel = 3;
                }
                return{
                    concept_id: targetConceptId,
                    difficulty_level: computedLevel,
                    question_text: m.question_text,
                    options: JSON.stringify(m.options),
                    correct_option: correctIndexPointer
                };
                });
                const { error: questionInsertError } = await supabase
                    .from("questions")
                    .insert(questionsPayload);

                if(questionInsertError){
                    console.error(`[DATABASE ERROR] Failed writing questions for concept ${targetConceptId}:`, questionInsertError);
                }
                const Flashcard = entry.flashcards?.[0];
                if(Flashcard){
                    await supabase.from("flashcards").insert({
                        concept_id: targetConceptId,
                        front_text: Flashcard.front,
                        back_text: Flashcard.back
                    });
                }
            }
            console.log("Everything is working fine!");
            return { success: true, stage: "Question and flashcards generation" };
        }

        let urlAnalysis = checkYoutubeUrl(url);

        await job.updateProgress(30);

        if(urlAnalysis.error){
            console.log("URL Analysis Error: ",urlAnalysis.error);
            throw new Error(`Invalid URL parsed: ${urlAnalysis.error}`);
        }

        const isChildJob = job.data.isChildJob || false;

        if(urlAnalysis.data.type === "playlist" && !isChildJob){
            console.log("Playlist detected, fetching Videos...");
            let playlistId = urlAnalysis.data.id;
            
            const { error: playlistDbError } = await supabase
                .from('playlists')
                .insert({
                    id: playlistId, 
                    title: "Playlist"
                });
            console.log("below databse playlist push ");
            if(playlistDbError){
                if(playlistDbError.code === '23505'){
                    console.log(`Playlist ${playlistId} already indexed in DB. Proceeding to video sync...`);
                }else{
                    // If it's a completely different database failure, crash safely
                    throw playlistDbError;
                }
            }
            const videoIdsObj = await fetchPlaylistVideoIds(playlistId);
            const videoIds = videoIdsObj.data;


            if(!videoIds || !Array.isArray(videoIds)){
                throw new Error("Failed to extract video array from playlist target resource.");
            }

            for(let videoId of videoIds){
                const singleVideoUrl = `https://www.youtube.com/watch?v=${videoId}`;
                await ingestQueue.add("ingest-job",{url:singleVideoUrl,playlistId:playlistId,isChildJob:true});
            }
            await job.updateProgress(100);
            return { success: true,data:null, error : null};
        }

        //if worker is processing a single video
        
        let transcriptObj = await fetchSingleVideoTranscript(urlAnalysis.data.id);
        let transcript = transcriptObj.data.item;
        let exactVideoMinutes = transcriptObj.data.videoMinutes;
        await job.updateProgress(40);

        //inserting videoId and userId in the database
        const { error: videoDbError } = await supabase
                .from('videos')
                .insert({
                    video_id:urlAnalysis.data.id, 
                    user_id:userId
                });

        let cleanedTextObj = cleanTranscript(transcript);
        let cleanedText = cleanedTextObj.data;
        await job.updateProgress(60);

        let chunksObj = chunkText(cleanedText);
        let chunks = chunksObj.data;
        await job.updateProgress(70);

        let embedVectorObj = await embedChunks(chunks);
        let embedVector = embedVectorObj.data;
        await job.updateProgress(80);

        console.log(`Writing vectors and relational text segments to Supabase...`);
        try{
            let insertPayload = chunks.map((chunkText,index)=>{
                return{
                    playlist_id:playlistId||null,   //this playlist id for single video will be fetched from the first line of this function (see at top)
                    video_id:urlAnalysis.data.id,
                    content:chunkText,
                    start_time:0,
                    embedding:embedVector[index],
                };
            });

            //single bulk insertion
            const { data, error } = await supabase
            .from('chunks') 
            .insert(insertPayload);

            if(error){
                throw error;
                //throw new Error(`Supabase Vector Insertion Failed: ${error.message}`);
            }
            console.log(`Successfully indexed ${insertPayload.length} vectors into pgvector.`);
            console.log(`Ingestion pipeline completed for playlist: ${playlistId}. Dispatching concept extraction...`);
            await ingestQueue.add("extract-concepts",
                {
                    chunks:chunks,
                    playlistId:playlistId,
                    videoId:urlAnalysis.data.id,
                    videoMinutes: exactVideoMinutes,
                },
                {attempts:3,backoff:{type:"exponential",delay:5000}});

            await job.updateProgress(100);
            return { success: true, stage: "video-ingestion-complete" };
        }
        catch(dbError){
            console.error(dbError);
            console.error("CAUSE:", dbError.cause);
            console.error("Database Cascade Failure:", dbError);
            throw dbError;
        }
    }catch(error){
        console.error(`[CRITICAL WORKER FAILURE] Job ID ${job.id} failed!`);
        console.error(error.stack || error);    //this is for out debugging
        throw new Error(`Worker failed: ${error.message}`); //we're throwing the error again so that the bullMQ catches it again inside BullMQ's internal execution engine.
        //so that it may be notified that the job wasn't finished.
    }
},{connection});

export {ingestQueue,connection};


function similarity(vectorA,vectorB){
    let dotProd = 0;
    let normA = 0;
    let normB = 0;
    for(let i = 0; i<vectorA.length; i++){
        dotProd += vectorA[i]*vectorB[i];
        normA += vectorA[i]*vectorA[i];
        normB += vectorB[i]*vectorB[i];
    }
    if(normA == 0 || normB == 0) return 0;
    let similarity = dotProd/(Math.sqrt(normA)*Math.sqrt(normB));
    return similarity;
}
