import {Queue,Worker} from "bullmq";
import path from "path";
import IORedis from "ioredis";
import dotenv from "dotenv";
import { createClient } from "@supabase/supabase-js";

import {checkYoutubeUrl} from "../services/fetchTranscript.js";
import {fetchSingleVideoTranscript, fetchPlaylistVideoIds} from "../services/fetchTranscript.js";
import { cleanTranscript,chunkText } from "../services/chunkText.js";
import { embedChunks } from "../services/embedChunks.js";
import { extractConcepts } from "../services/extractConcepts.js";
import { title } from "process";

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const REDIS_URL = process.env.REDIS_URL || 'redis://127.0.0.1:6379';

const connection = new IORedis(REDIS_URL,{maxRetriesPerRequest: null}); // Required by BullMQ to prevent connection drops

const ingestQueue = new Queue("youtube-ingestion",{connection});    //Queue creation

const ingestWorker = new Worker("youtube-ingestion",async (job)=>{  //Worker creation
    const {url,playlistId} = job.data;
    console.log(`Processing job with job id ${job.id} and url ${url}`);
    try{
        await job.updateProgress(10);
        
        //if the job is of concept extraction
        if(job.name == "extract-concepts"){
            let {chunks,playlistId} = job.data;
            const graphDataObj = await extractConcepts(chunks);
            const concepts = graphDataObj.concepts;
            const prerequisites = graphDataObj.prerequisites;
            const slugToPostgresIdMap = {}; //needed to map the prerequites source and target concept actual ids 
            //it is because the the id generated by LLM is slug-integer type and not a int,
            //int is assigned directly by postgres so we need that to resue in prerequisites table
            let insertPayloadForConcepts = concepts.map((concept,index)=>{
                return{
                    playlist_id:playlistId,
                    name:concept.name,
                    description: concept.description,
                };
            });

            if (insertPayloadForConcepts.length > 0) {
                const {data:insertedConcepts, error:conceptError} = await supabase.from('concepts').insert(insertPayloadForConcepts)
                .select("id,name");   //this tells supabase to return actual ids and name

                if(conceptError) throw conceptError;
                //finding actual ids for slug-ids
                insertedConcepts.forEach(dbConcept=>{
                    const matchingLlmConcept = concepts.find(c=>c.name === dbConcept.name);
                    if(matchingLlmConcept){
                        //lhs is a string, rhs is a number
                        slugToPostgresIdMap[matchingLlmConcept.id] = dbConcept.id;
                    }
                });
            }

            let insertPayloadForPrerequisites = prerequisites.map((prerequisite,index)=>{
                return{
                    playlist_id:playlistId,
                    source_concept_id:slugToPostgresIdMap[prerequisite.source],
                    target_concept_id:slugToPostgresIdMap[prerequisite.target],
                };
            }).filter(edge => edge.source_concept_id !== undefined && edge.target_concept_id !== undefined);
            //this above line is a extra safety check which is added to filter out only non undefined key value pairs
            const {data:insertedPrerequisites, error:prerequisitesError} = await supabase.from('concept_edges').insert(insertPayloadForPrerequisites);
            if(prerequisitesError) throw prerequisitesError;

            console.log(`Knowledge graph synthesis finalized successfully.`);

            return { success: true, stage: "graph-extraction" };

        }

        let urlAnalysis = checkYoutubeUrl(url);

        await job.updateProgress(30);

        if(urlAnalysis.error){
            console.log("URL Analysis Error: ",urlAnalysis.error);
            throw new Error(`Invalid URL parsed: ${urlAnalysis.error}`);
        }

        const isChildJob = job.data.isChildJob || false;

        if(urlAnalysis.data.type === "playlist" && !isChildJob){
            console.log("Playlist detected, fetching Videos...");
            let playlistId = urlAnalysis.data.id;
            
            const { error: playlistDbError } = await supabase
                .from('playlists')
                .insert({
                    id: playlistId, 
                    title: "Playlist"
                });
            console.log("below databse playlist push ");
            if(playlistDbError){
                if(playlistDbError.code === '23505'){
                    console.log(`Playlist ${playlistId} already indexed in DB. Proceeding to video sync...`);
                }else{
                    // If it's a completely different database failure, crash safely
                    throw playlistDbError;
                }
            }
            const videoIdsObj = await fetchPlaylistVideoIds(playlistId);
            const videoIds = videoIdsObj.data;


            if(!videoIds || !Array.isArray(videoIds)){
                throw new Error("Failed to extract video array from playlist target resource.");
            }

            for(let videoId of videoIds){
                const singleVideoUrl = `https://www.youtube.com/watch?v=${videoId}`;
                await ingestQueue.add("ingest-job",{url:singleVideoUrl,playlistId:playlistId,isChildJob:true});
            }
            await job.updateProgress(100);
            return { success: true,data:null, error : null};
        }

        //if worker is processing a single video
        
        let transcriptObj = await fetchSingleVideoTranscript(urlAnalysis.data.id);
        let transcript = transcriptObj.data;
        await job.updateProgress(40);

        let cleanedTextObj = cleanTranscript(transcript);
        let cleanedText = cleanedTextObj.data;
        await job.updateProgress(60);

        let chunksObj = chunkText(cleanedText);
        let chunks = chunksObj.data;
        await job.updateProgress(70);

        let embedVectorObj = await embedChunks(chunks);
        let embedVector = embedVectorObj.data;
        await job.updateProgress(80);

        console.log(`Writing vectors and relational text segments to Supabase...`);
        try{
            let insertPayload = chunks.map((chunkText,index)=>{
                return{
                    playlist_id:playlistId||null,   //this playlist id for single video will be fetched from the first line of this function (see at top)
                    video_id:urlAnalysis.data.id,
                    content:chunkText,
                    start_time:0,
                    embedding:embedVector[index],
                };
            });

            //single bulk insertion
            const { data, error } = await supabase
            .from('chunks') 
            .insert(insertPayload);

            if(error){
                throw error;
                //throw new Error(`Supabase Vector Insertion Failed: ${error.message}`);
            }
            console.log(`Successfully indexed ${insertPayload.length} vectors into pgvector.`);
            console.log(`Ingestion pipeline completed for playlist: ${playlistId}. Dispatching concept extraction...`);
            await ingestQueue.add("extract-concepts",
                {chunks:chunks,playlistId:playlistId},
                {attempts:3,backoff:{type:"exponential",delay:5000}});

            await job.updateProgress(100);
            return { success: true, stage: "video-ingestion-complete" };
        }
        catch(dbError){
            console.error(dbError);
            console.error("CAUSE:", dbError.cause);
            console.error("Database Cascade Failure:", dbError);
            throw dbError;
        }
    }catch(error){
        console.error(`[CRITICAL WORKER FAILURE] Job ID ${job.id} failed!`);
        console.error(error.stack || error);    //this is for out debugging
        throw new Error(`Worker failed: ${error.message}`); //we're throwing the error again so that the bullMQ catches it again inside BullMQ's internal execution engine.
        //so that it may be notified that the job wasn't finished.
    }
},{connection});

export {ingestQueue,connection};
